name: sign_up_with_getx
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  dio: ^4.0.6
  cupertino_icons: ^1.0.6
  intl: ^0.17.0
  get: ^4.6.5
  get_storage: ^2.0.3
  equatable: ^2.0.3
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.4
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^6.2.0
  flutter_launcher_icons: ^0.11.0
  freezed: ^2.3.2

  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/